name: CI/CD to AWS ECS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1 # TODO: Update with your AWS region
      ECR_REPOSITORY: addressbook # TODO: Update with your ECR repository name
      ECS_CLUSTER: addressbook-cluster # TODO: Update with your ECS cluster name
      ECS_SERVICE: addressbook-service # TODO: Update with your ECS service name
      ECS_TASK_DEFINITION: addressbook-task # TODO: Update with your ECS task definition family
      CONTAINER_NAME: addressbook # TODO: Update with your ECS container name

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test with Maven
        run: mvn -B clean verify
        working-directory: addressbook-rest-service

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ env.AWS_REGION }}

      - name: Build, tag, and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          IMAGE_TAG=latest
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG ./addressbook-rest-service
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Download ECS task definition
        run: |
          aws ecs describe-task-definition \
            --region $AWS_REGION \
            --task-definition $ECS_TASK_DEFINITION \
            --query 'taskDefinition' \
            > task-definition.json

      - name: Update task definition with new image
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Deploy to ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
          region: ${{ env.AWS_REGION }}

# ---
# Before using this workflow, make sure to:
# 1. Create an ECR repository named 'addressbook' (or update ECR_REPOSITORY above)
# 2. Create an ECS cluster and service (or update ECS_CLUSTER and ECS_SERVICE above)
# 3. Create a task definition family (or update ECS_TASK_DEFINITION above)
# 4. Set up GitHub secrets: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
# 5. Update CONTAINER_NAME if your ECS task definition uses a different name 